### ISSUE TITLE
Change extension search algo

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-quarkus#8]
We need to find the most relevant search algo to search extension..

**Comment by ia3andy** [comment]
We have those fields:
- groupId
- artifactId
- shortName
- name
- category
- labels
- description

We need to know which fields to match and how (full match/startWith/contains)
and what fields to use for the sort order.

**Comment by ia3andy** [comment]
example of item:
```yaml
  name: RESTEasy JAX-RS
  description: "REST framework implementing JAX-RS and more"
  labels:
     - resteasy
    - jaxrs
    - web
    - rest
  groupId: io.quarkus
  artifactId: quarkus-resteasy
  category: Web
```
